server:
  port: 8080

spring:
  application:
    name: web-forum
  datasource:
    url: jdbc:h2:mem:web_forum_db
    username: admin
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.format_sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false

springdoc:
  swagger-ui:
    path: /swagger-ui
